### ISSUE TITLE
Creer une animation d'un curseur qui se deplace en 2 frame sur l'entrée du nom

### ISSUE THREAD

**Issue by navet56** [jlppc/OpMon#21]
# Description du bug et explication du moment ou il est survenu:
Creer une animation d'un curseur qui se deplace en 2 frame sur l'entrée du nom
Ce n'est pas compliquer vu que c'est deja codé faut juste baisser la vitesse et le nombres de frames et changer le sprite

**Comment by jlppc** [comment]
Ajout non prévu pour l'instant
