### ISSUE TITLE
Ajouter le plein écran

### ISSUE THREAD

**Issue by jlppc** [jlppc/OpMon#23]
# Description de l'ajout :
Il faut ajouter le plein écran, mais sans que l'image se déforme. Il faut qu'elle reste carrée. Il y aura besoin d'un redemmarage du programme pour appliquer le plein écran.

**Comment by navet56** [comment]
Desolé

**Comment by jlppc** [comment]
Issue fermée temporairement, pour la réouvrir plus tard
