### ISSUE TITLE
Bug : Les accents bugent lors de la lecture du fichier keys

### ISSUE THREAD

**Issue by jlppc** [jlppc/OpMon#3]
# Description du bug et explication du moment ou il est survenu:
Les accents ont un problème d'affichage pendant les dialogues. Cela survient lors de la lecture du fichier keys.rkeys, c'est un problème d'encodage.

**Comment by jlppc** [comment]
Corrigé : Venait d'une incompatibilité d'encodage

**Comment by navet56** [comment]
En fait, cela recommence des que le fichier est modifier via GitHub

**Comment by jlppc** [comment]
Bug corrigé : 06092ace
Changement de l'encodage d'écriture des dialogues en UTF-8
