### ISSUE TITLE
Bug : Le personnage traverse des murs

### ISSUE THREAD

**Issue by jlppc** [jlppc/OpMon#33]
# Description du bug et explication du moment ou il est survenu:
Le personnage, en forcant, peut traverser des maisons et des murs. Peut causer des crash en cas de dépassement de la map.

**Comment by navet56** [comment]
Le scrolling est probablement le probleme car cela decalle les collisions, le haut des maisons est trop bas au niveau des collisions et le bas des maisons aussi, par exemple.

**Comment by jlppc** [comment]
Bug corrigé (Pull request #35)
